### ISSUE TITLE
Suggestions for shooter subsystem

### ISSUE THREAD

**Issue by adamrubinfeld** [litehed/FTC-Goal-2020#5]
For more accuracy in the shooting my suggestion is to add control of the RPM you can do that by set the motor object to ExDcMotor and do msetVelocity(<ticks per second>) and that have only three lines of code or you can write PIDF control by your self my suggestion is do the first thing

**Comment by JIceberg** [comment]
We utilize FTCLib, a comprehensive library for FTC. The SDK features and PIDF control are wrapped or written there.
